# Numpy, array

## 1. Numpy 기본 정보
### 1-1. Numpy n차원
1. 1차원 축(행) : axis0 -> Vector
1. 2차원 축(열) : axis1 -> Matrix
1. 3차원 축(채널) : axis2 -> Tensor(3차원 이상)
1. numpy는 `동일한 데이터 타입의 요소`로 이뤄진다.
    - list 타입은 [1, 2, 'code', [5, 6]] 처럼 list 안에 문자열이나 리스트 요소가 들어갈 수 있지만
      numpy의 배열(array)은 [1, 2, 3, 4] 처럼 동일한 타입의 요소만 들어갈 수 있다.
1. array의 길이는 고정되어 있다.
    - list의 경우 .append()를 통해 데이터를 추가하여 길이를 변경할 수 있지만, 배열의 경우 길이를 변경하려면 새롭게 배열을 생성해야 한다.

In [1]:
import numpy as np
# Numpy 기본1
list = [0, 1, 2, 3]
# print(list)

array = np.array(list) # array라는 변수는 numpy 데이터이므로 size, dtype과 같은 다양한 함수 제공
print(array.size)
print(array.dtype)
print(array[2])

4
int64
2


In [2]:
# Numpy 기본2
import numpy as np
print("1차원 배열 만들기 0~4까지")
array1 = np.arange(5)
print(array1)

print("\n2차원 zeroes를 사용하여 0의 실수형태 배열 만들기")
array2 = np.zeros((4, 4), dtype=float) # 4*4 2차원 배열형태, 실수형태로
print(array2)

print("\n2차원 ones를 사용하여 1의 실수형태 배열 만들기")
array3 = np.ones((4, 4), dtype=float)
print(array3)

# 0부터 49까지 랜덤하게 출력하기
print("\nrow 5개, column 6개의 0~49 랜덤정수 2차원 배열 만들기 ")
array4 = np.random.randint(1, 51, (5, 6))
print(array4)

# 평균이 0, 표준편차 1인 표준 정규
print("\nrow 3개, column 3개의 평균이 0, 표준편차 1인 2차원 배열 만들기")
print("np.random.normal은 numpy에서 정규분포를 따르는 난수를 생성할 때 사용")
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

1차원 배열 만들기 0~4까지
[0 1 2 3 4]

2차원 zeroes를 사용하여 0의 실수형태 배열 만들기
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2차원 ones를 사용하여 1의 실수형태 배열 만들기
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

row 5개, column 6개의 0~49 랜덤정수 2차원 배열 만들기 
[[13 16 20 44 40 50]
 [38 17 33 34 29 39]
 [45 27 44 18  1 20]
 [48 49 24 15 49 29]
 [46  5 13 40 47 25]]

row 3개, column 3개의 평균이 0, 표준편차 1인 2차원 배열 만들기
np.random.normal은 numpy에서 정규분포를 따르는 난수를 생성할 때 사용
[[ 0.65689053  0.72013915  0.25158186]
 [-0.19847971 -0.0417849  -2.13407857]
 [-0.61575475  0.226677   -0.27315758]]


In [3]:
# Numpy 기본3 배열 합치기
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.concatenate([array1, array2])

array7 = np.concatenate([array1, array2], axis=0)
print("배열은 np.concatenate함수를 이용해 특정 축(axis=n)을 지정하여 하나의 배열로 만들 수 있음")
print(array3)

# Numpy 기본4 배열 변경하기 reshape

array4 = np.array([1, 2, 3, 4]) # 1차원 벡터 형태 데이터를
array5 = array4.reshape((2, 2)) # 2차원 배열형태 데이터로 변경
print("\n배열은 np.reshape 함수를 이용해 원소의 수는 유지하며 차원 형태를 변경할 수 있음")
print("1차원 배열 :\n", array4)
print("2차원 배열 :\n", array5)

배열은 np.concatenate함수를 이용해 특정 축(axis=n)을 지정하여 하나의 배열로 만들 수 있음
[1 2 3 4 5 6]

배열은 np.reshape 함수를 이용해 원소의 수는 유지하며 차원 형태를 변경할 수 있음
1차원 배열 :
 [1 2 3 4]
2차원 배열 :
 [[1 2]
 [3 4]]


**배열의 차원이 일치하지 않은 상태에서 배열끼리 합칠(concatenate)경우**
 
기본적으로 차원이 서로 일치하지 않는 배열을 합칠 경우 오류가 발생한다.
(1,4), (4,2) 형태의 두 배열은 각각 (1row, 4col), (4row, 2col)로 서로 열과 행이 맞지 않는다.
이 상태에서 `axis=0`으로 결합한다는건 두 열의 수가 같아야 하지만, 두 배열의 열은 4, 2로 서로 일치하지 않는다.
`axis=1` 으로 결합할려면 행의 수가 같아야 하지만, 두 배열의 행은 1, 4로 일치하지 않는다.

In [4]:
import numpy as np
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(4, 2)

array3 = np.concatenate([array1, array2], axis=0)
print(array1)
print('-----------------')
print(array2)
print('-----------------')
print(array3)



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

## 2. Array 속성 확인
### 2-1. 자료형 확인
1. type(array)를 사용
### 2-2. 배열 크기 확인
1. array.size를 사용
### 2-3. 배열 모양
1. array.shape를 사용

In [5]:
array1 = np.array([1, 2, 3, 4, 5, 6])
print("확인할 배열 :", array1)
# 자료형 확인
print("\n2-1. 배열의 자료형 확인하기")
print(type(array1))

# 배열의 크기 확인
print("\n2-2. 배열의 크기 확인하기")
print(array1.size)

# 배열의 모양 확인
print("\n2-3. 배열의 모양 확인하기")
print(array1.shape)

확인할 배열 : [1 2 3 4 5 6]

2-1. 배열의 자료형 확인하기
<class 'numpy.ndarray'>

2-2. 배열의 크기 확인하기
6

2-3. 배열의 모양 확인하기
(6,)
